import { METHODS, emptyState, today, currentPeriod, money, displayDate, periodLabel, addEmployee, addAdvance, reverseTransaction, employeeSummary, companySummary, settle } from './core.js';

const KEY = 'vetan-ledger-v1';
let state;
try { state = { ...emptyState(), ...JSON.parse(localStorage.getItem(KEY) || 'null') }; } catch { state = emptyState(); }
let page = 'dashboard';
let period = currentPeriod();
const $ = (q, root = document) => root.querySelector(q);
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[c]);
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const toast = message => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); };
const person = e => `<div class="person"><span class="avatar">${esc(e.name.slice(0, 1).toUpperCase())}</span><div><b>${esc(e.name)}</b><small>${esc(e.employeeCode)}${e.department ? ` · ${esc(e.department)}` : ''}</small></div></div>`;
const badge = status => `<span class="badge ${status.toLowerCase().replaceAll(' ', '-')}">${esc(status)}</span>`;
const options = (activeOnly = true) => state.employees.filter(e => !activeOnly || e.active).map(e => `<option value="${e.id}">${esc(e.name)} — ${esc(e.employeeCode)}</option>`).join('');
const head = (eyebrow, title, subtitle, actions = '') => `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${subtitle}</p></div><div class="actions">${actions}</div></div>`;
const tableEmpty = (title, note) => `<div class="empty"><div>▥</div><b>${title}</b>${note}</div>`;

function render() {
  $('#periodPicker').value = period;
  document.querySelectorAll('#nav button').forEach(b => b.classList.toggle('active', b.dataset.page === page));
  const renderers = { dashboard, employees, advance, transactions, settlement, reports, settings };
  $('#page').innerHTML = `<section class="content">${renderers[page]()}</section>`;
  bindPage();
}

function dashboard() {
  const s = companySummary(state, period);
  const recent = state.transactions.filter(t => t.period === period).sort((a,b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 6);
  const todayTotal = state.transactions.filter(t => !t.reversed && t.date === today()).reduce((n,t) => n + t.amount, 0);
  return `${head('Business overview', `Good ${new Date().getHours() < 12 ? 'morning' : 'evening'}`, `${periodLabel(period)} salary position`, `<button class="btn" data-go="employees">+ Add Employee</button><button class="btn primary" data-go="advance">+ Add Advance</button>`)}
  <div class="metrics"><div class="metric"><label>Active employees <span>♙</span></label><strong>${s.activeCount}</strong><small>Current workforce</small></div><div class="metric"><label>Salary liability <span>₹</span></label><strong>${money(s.salary)}</strong><small>${periodLabel(period)}</small></div><div class="metric"><label>Advances given <span>↗</span></label><strong>${money(s.advances)}</strong><small>Today: ${money(todayTotal)}</small></div><div class="metric highlight ${s.payable < 0 ? 'negative' : ''}"><label>Remaining payable <span>◉</span></label><strong>${money(s.payable)}</strong><small>${s.payable < 0 ? `Over advance ${money(-s.payable)}` : 'After advances & adjustments'}</small></div></div>
  <div class="card no-print" style="margin-bottom:18px"><div class="card-body"><div class="quick-form"><div class="field"><label>Employee</label><select id="quickEmployee"><option value="">Select employee…</option>${options()}</select></div><div class="field"><label>Amount (₹)</label><input id="quickAmount" type="number" min="1" placeholder="2,000"></div><div class="field"><label>Method</label><select id="quickMethod">${METHODS.map(m=>`<option ${m===state.settings.defaultMethod?'selected':''}>${m}</option>`)}</select></div><button class="btn primary" id="quickSave">Save advance</button></div></div></div>
  <div class="grid-2"><div class="card"><div class="card-head"><h2>Recent transactions</h2><button class="link" data-go="transactions">View all →</button></div>${recent.length ? `<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Method</th><th>Amount</th></tr></thead><tbody>${recent.map(t=>{const e=state.employees.find(x=>x.id===t.employeeId);return `<tr class="${t.reversed?'subtle':''}"><td>${e?person(e):'Unknown'}${t.reversed?badge('Reversed'):''}</td><td>${displayDate(t.date)}</td><td>${esc(t.method)}</td><td class="amount">${t.reversed?'<s>':''}${money(t.amount)}${t.reversed?'</s>':''}</td></tr>`}).join('')}</tbody></table></div>`:tableEmpty('No payments this period','Save the first advance using the quick form above.')}</div>
  <div class="card"><div class="card-head"><h2>Highest advances</h2><span class="subtle">This period</span></div><div class="card-body">${s.rows.filter(r=>r.advances).sort((a,b)=>b.advances-a.advances).slice(0,5).map(r=>`<div class="rank-row"><span>${esc(r.employee.name)}</span><b>${money(r.advances)}</b><div class="progress"><span style="width:${Math.min(100,r.salary?r.advances/r.salary*100:100)}%"></span></div></div>`).join('') || tableEmpty('Nothing to rank','Advances will appear here.')}</div></div></div>`;
}

function employees() {
  return `${head('People', 'Employees', 'Manage salary profiles without losing financial history.', `<button class="btn primary" id="addEmployee">+ Add Employee</button>`)}<div class="filterbar"><input id="employeeFilter" placeholder="Search name, ID, department…"><select id="employeeStatus"><option value="all">All employees</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button class="btn" id="exportEmployees">Export CSV</button><button class="btn" id="importEmployees">Import CSV</button><input type="file" id="employeeFile" accept=".csv" hidden></div><div class="card" id="employeeTable">${employeeRows()}</div>`;
}
function employeeRows(query='', status='all') {
  const list=state.employees.filter(e=>(status==='all'||(status==='active')===e.active)&&`${e.name} ${e.employeeCode} ${e.department}`.toLowerCase().includes(query.toLowerCase()));
  if(!list.length)return tableEmpty('No employees found','Add an employee or change the filters.');
  return `<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Joined</th><th>Monthly salary</th><th>Current balance</th><th>Status</th><th></th></tr></thead><tbody>${list.map(e=>{const s=employeeSummary(state,e,period);return `<tr><td>${person(e)}</td><td>${displayDate(e.joiningDate)}</td><td class="amount">${money(s.salary)}</td><td class="amount ${s.payable<0?'negative':''}">${money(s.payable)}${s.payable<0?'<small class="subtle">Over advance</small>':''}</td><td>${badge(e.active?'Active':'Inactive')}</td><td><button class="link" data-ledger="${e.id}">Ledger</button> <button class="link" data-edit-employee="${e.id}">Edit</button></td></tr>`}).join('')}</tbody></table></div>`;
}

function advance() { return `${head('Fast entry','Add advance / payment','Select employee, enter amount, and save in seconds.')}<div class="advance-hero"><h2 style="margin-top:0">Record a payment</h2><p>The ledger, dashboard, settlement, and reports update automatically.</p><form id="advanceForm" class="quick-form"><div class="field"><label>Employee</label><select name="employeeId" required><option value="">Search / select…</option>${options()}</select></div><div class="field"><label>Amount (₹)</label><input name="amount" type="number" min="0.01" step="0.01" required autofocus></div><div class="field"><label>Date</label><input name="date" type="date" value="${today()}" required></div><div class="field"><label>Payment method</label><select name="method">${METHODS.map(m=>`<option ${m===state.settings.defaultMethod?'selected':''}>${m}</option>`)}</select></div><button class="btn primary">Save payment</button><div class="field full"><label>Note (optional)</label><input name="note" placeholder="e.g. Personal advance"></div></form></div><div class="callout"><b>Duplicate protection is on.</b> The save button locks while processing and each submission carries a unique request ID.</div>`; }

function transactions() {
  const rows=filteredTransactions();
  return `${head('Audit trail','Transactions','Every payment remains traceable; corrections are recorded as reversals.',`<button class="btn primary" data-go="advance">+ Add Advance</button>`)}<div class="filterbar"><input id="txnSearch" placeholder="Employee, ID or amount"><select id="txnMethod"><option value="">All methods</option>${METHODS.map(m=>`<option>${m}</option>`)}</select><input id="txnFrom" type="date"><input id="txnTo" type="date"><button class="btn" id="exportTransactions">Export CSV</button></div><div class="card" id="transactionTable">${transactionRows(rows)}</div>`;
}
function filteredTransactions(filters={}) { return state.transactions.filter(t=>{const e=state.employees.find(x=>x.id===t.employeeId);return (!filters.q||`${e?.name} ${e?.employeeCode} ${t.amount}`.toLowerCase().includes(filters.q.toLowerCase()))&&(!filters.method||t.method===filters.method)&&(!filters.from||t.date>=filters.from)&&(!filters.to||t.date<=filters.to)}).sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt.localeCompare(a.createdAt)); }
function transactionRows(rows){if(!rows.length)return tableEmpty('No transactions found','Try another filter or record an advance.');return `<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Date / period</th><th>Method</th><th>Note</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(t=>{const e=state.employees.find(x=>x.id===t.employeeId);return `<tr><td>${e?person(e):'Unknown'}</td><td>${displayDate(t.date)}<small class="subtle">${periodLabel(t.period)}</small></td><td>${esc(t.method)}</td><td>${esc(t.note||'—')}</td><td class="amount">${money(t.amount)}</td><td>${badge(t.reversed?'Reversed':'Posted')}</td><td>${t.reversed?`<small title="${esc(t.reversalReason)}">Corrected</small>`:`<button class="link danger" data-reverse="${t.id}">Reverse</button>`}</td></tr>`}).join('')}</tbody></table></div>`}

function settlement(){const s=companySummary(state,period);return `${head('Payroll close','Monthly settlement',`Review and settle ${periodLabel(period)} salaries.`,`<button class="btn" id="exportSettlement">Export CSV</button>`)}<div class="metrics"><div class="metric"><label>Salary</label><strong>${money(s.salary)}</strong></div><div class="metric"><label>Advances</label><strong>${money(s.advances)}</strong></div><div class="metric"><label>Final payable</label><strong>${money(s.payable)}</strong></div><div class="metric"><label>Salary paid</label><strong>${money(s.paid)}</strong></div></div><div class="card">${s.rows.length?`<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Applicable salary</th><th>Advances</th><th>Adjustments</th><th>Final payable</th><th>Status</th><th></th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${person(r.employee)}</td><td class="amount">${money(r.salary)}</td><td>${money(r.advances)}</td><td>${money(r.adjustments)}</td><td class="amount ${r.payable<0?'negative':''}">${money(r.payable)}</td><td>${badge(r.status)}</td><td><button class="link" data-settle="${r.employee.id}">${r.status==='Pending'?'Mark paid':'View / update'}</button></td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No employees','Add an employee to prepare payroll.')}</div>`}

function reports(){const s=companySummary(state,period);return `${head('Analysis','Reports',`Company-wide financial summary for ${periodLabel(period)}.`,`<button class="btn" id="printReport">Print / PDF</button><button class="btn primary" id="exportReport">Export CSV</button>`)}<div class="metrics"><div class="metric"><label>Total salary</label><strong>${money(s.salary)}</strong></div><div class="metric"><label>Total advances</label><strong>${money(s.advances)}</strong></div><div class="metric"><label>Paid</label><strong>${money(s.paid)}</strong></div><div class="metric ${s.payable<0?'negative':''}"><label>Net payable</label><strong>${money(s.payable)}</strong></div></div><div class="card"><div class="card-head"><h2>Employee-wise reconciliation</h2><span>${s.rows.filter(r=>r.status==='Paid').length} paid · ${s.rows.filter(r=>r.status!=='Paid').length} pending</span></div>${s.rows.length?`<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Salary</th><th>Advances</th><th>Adjustments</th><th>Payable</th><th>Paid</th><th>Status</th></tr></thead><tbody>${s.rows.map(r=>`<tr><td>${person(r.employee)}</td><td>${money(r.salary)}</td><td>${money(r.advances)}</td><td>${money(r.adjustments)}</td><td class="amount">${money(r.payable)}</td><td>${money(r.paid)}</td><td>${badge(r.status)}</td></tr>`).join('')}</tbody></table></div>`:tableEmpty('No report data','Add employees to begin.')}</div>`}

function settings(){return `${head('Administration','Settings','Business preferences, backups, and safe data portability.')}<div class="settings-list"><div class="card"><div class="card-head"><h2>Business settings</h2></div><form id="settingsForm" class="card-body form-grid"><div class="field full"><label>Company name</label><input name="companyName" value="${esc(state.settings.companyName)}" required></div><div class="field"><label>Currency</label><input value="INR — Indian Rupee (₹)" disabled></div><div class="field"><label>Default payment method</label><select name="defaultMethod">${METHODS.map(m=>`<option ${m===state.settings.defaultMethod?'selected':''}>${m}</option>`)}</select></div><div class="field full"><label>Salary period</label><input value="Calendar month" disabled></div><div class="field full"><button class="btn primary">Save settings</button></div></form></div><div class="card"><div class="card-head"><h2>Backup & restore</h2></div><div class="card-body"><p>Download a complete JSON backup regularly. Restoring replaces the data on this device after validation.</p><div class="actions"><button class="btn primary" id="backup">Download backup</button><button class="btn" id="restore">Restore backup</button><input id="restoreFile" type="file" accept=".json" hidden></div></div></div><div class="callout"><b>Designed for the cheapest iPhone setup:</b> add this site to the iOS Home Screen for an app-like, offline experience. Data lives on this device, so keep regular backups.</div></div>`}

function showModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')};function closeModal(){$('#modal').classList.add('hidden')}
function employeeModal(employee){showModal(`<h2>${employee?'Edit employee':'Add employee'}</h2><form id="employeeForm" class="form-grid"><input type="hidden" name="id" value="${employee?.id||''}"><div class="field full"><label>Employee name *</label><input name="name" value="${esc(employee?.name||'')}" required></div><div class="field"><label>Monthly salary (₹) *</label><input name="monthlySalary" type="number" min="0" step=".01" value="${employee?.monthlySalary??''}" required></div><div class="field"><label>Joining date *</label><input name="joiningDate" type="date" value="${employee?.joiningDate||today()}" required></div><div class="field"><label>Mobile</label><input name="mobile" inputmode="tel" value="${esc(employee?.mobile||'')}"></div><div class="field"><label>Department / Job</label><input name="department" value="${esc(employee?.department||'')}"></div><div class="field full"><label>Notes</label><textarea name="notes">${esc(employee?.notes||'')}</textarea></div>${employee?`<div class="field full"><label><input name="active" type="checkbox" ${employee.active?'checked':''} style="width:auto"> Active employee</label></div>`:''}<div class="modal-actions field full"><button type="button" class="btn modal-cancel">Cancel</button><button class="btn primary">Save employee</button></div></form>`)}
function ledgerModal(id){const e=state.employees.find(x=>x.id===id),s=employeeSummary(state,e,period),tx=filteredTransactions().filter(t=>t.employeeId===id&&t.period===period);showModal(`<div class="eyebrow">${esc(e.employeeCode)} · ${periodLabel(period)}</div><h2>${esc(e.name)} ledger</h2><div class="metrics" style="grid-template-columns:repeat(3,1fr)"><div class="metric"><label>Salary</label><strong>${money(s.salary)}</strong></div><div class="metric"><label>Taken</label><strong>${money(s.advances)}</strong></div><div class="metric ${s.payable<0?'negative':''}"><label>Remaining</label><strong>${money(s.payable)}</strong></div></div>${transactionRows(tx)}<div class="modal-actions"><button class="btn" id="ledgerCsv">Export CSV</button><button class="btn primary modal-cancel">Close</button></div>`);$('#ledgerCsv').onclick=()=>downloadCsv(`${e.employeeCode}-${period}-ledger.csv`,tx.map(t=>({date:t.date,type:'Advance',method:t.method,amount:t.amount,note:t.note,status:t.reversed?'Reversed':'Posted'})))}
function settlementModal(id){const e=state.employees.find(x=>x.id===id),s=employeeSummary(state,e,period);showModal(`<div class="eyebrow">${periodLabel(period)}</div><h2>Settle ${esc(e.name)}</h2><div class="callout">${money(s.salary)} salary − ${money(s.advances)} advances + ${money(s.adjustments)} adjustments = <b>${money(s.payable)}</b></div><form id="settlementForm" class="form-grid"><input type="hidden" name="employeeId" value="${e.id}"><div class="field"><label>Adjustment (+ bonus / − deduction)</label><input name="adjustments" type="number" step=".01" value="${s.adjustments}"></div><div class="field"><label>Final amount paid</label><input name="amountPaid" type="number" min="0" step=".01" value="${s.paid||Math.max(0,s.payable)}" required></div><div class="field"><label>Payment date</label><input name="paymentDate" type="date" value="${s.settlement?.paymentDate||today()}" required></div><div class="field"><label>Method</label><select name="method">${METHODS.map(m=>`<option ${m===(s.settlement?.method||state.settings.defaultMethod)?'selected':''}>${m}</option>`)}</select></div><div class="field full"><label>Notes</label><input name="notes" value="${esc(s.settlement?.notes||'')}"></div><div class="modal-actions field full"><button type="button" class="btn modal-cancel">Cancel</button><button class="btn primary">Save settlement snapshot</button></div></form>`)}

function bindPage(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#quickSave')?.addEventListener('click',e=>saveAdvance({employeeId:$('#quickEmployee').value,amount:$('#quickAmount').value,date:today(),method:$('#quickMethod').value,note:'Quick entry'},e.currentTarget));$('#advanceForm')?.addEventListener('submit',e=>{e.preventDefault();saveAdvance(Object.fromEntries(new FormData(e.target)),e.submitter)});$('#addEmployee')?.addEventListener('click',()=>employeeModal());document.querySelectorAll('[data-edit-employee]').forEach(b=>b.onclick=()=>employeeModal(state.employees.find(e=>e.id===b.dataset.editEmployee)));document.querySelectorAll('[data-ledger]').forEach(b=>b.onclick=()=>ledgerModal(b.dataset.ledger));document.querySelectorAll('[data-settle]').forEach(b=>b.onclick=()=>settlementModal(b.dataset.settle));document.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>{const reason=prompt('Reason for reversal (required):');if(reason&&confirm('Reverse this transaction? The audit record will be kept.')){try{reverseTransaction(state,b.dataset.reverse,reason);save();toast('Transaction reversed');render()}catch(err){toast(err.message)}}});
  $('#employeeFilter')?.addEventListener('input',filterEmployees);$('#employeeStatus')?.addEventListener('change',filterEmployees);['txnSearch','txnMethod','txnFrom','txnTo'].forEach(id=>$(`#${id}`)?.addEventListener('input',filterTx));$('#exportEmployees')?.addEventListener('click',()=>downloadCsv('employees.csv',state.employees.map(e=>({employee_id:e.employeeCode,name:e.name,mobile:e.mobile,monthly_salary:e.monthlySalary,joining_date:e.joiningDate,department:e.department,status:e.active?'Active':'Inactive',notes:e.notes}))));$('#importEmployees')?.addEventListener('click',()=>$('#employeeFile').click());$('#employeeFile')?.addEventListener('change',importEmployees);$('#exportTransactions')?.addEventListener('click',()=>downloadCsv('transactions.csv',filteredTransactions().map(exportTxn)));$('#exportSettlement')?.addEventListener('click',()=>exportSummary('monthly-settlement'));$('#exportReport')?.addEventListener('click',()=>exportSummary('salary-report'));$('#printReport')?.addEventListener('click',()=>window.print());$('#backup')?.addEventListener('click',()=>download(`vetan-backup-${today()}.json`,JSON.stringify(state,null,2),'application/json'));$('#restore')?.addEventListener('click',()=>$('#restoreFile').click());$('#restoreFile')?.addEventListener('change',restoreBackup);$('#settingsForm')?.addEventListener('submit',e=>{e.preventDefault();state.settings={...state.settings,...Object.fromEntries(new FormData(e.target))};save();toast('Settings saved')});}
function go(p){page=p;$('.sidebar').classList.remove('open');render()};function filterEmployees(){$('#employeeTable').innerHTML=employeeRows($('#employeeFilter').value,$('#employeeStatus').value);bindPage()};function filterTx(){$('#transactionTable').innerHTML=transactionRows(filteredTransactions({q:$('#txnSearch').value,method:$('#txnMethod').value,from:$('#txnFrom').value,to:$('#txnTo').value}));bindPage()}
function saveAdvance(data,button){button.disabled=true;try{addAdvance(state,{...data,requestId:`ui_${Date.now()}_${Math.random()}`});save();toast(`Payment of ${money(data.amount)} saved`);page='dashboard';render()}catch(err){toast(err.message);button.disabled=false}}
function exportTxn(t){const e=state.employees.find(x=>x.id===t.employeeId);return {transaction_id:t.id,employee_id:e?.employeeCode,employee:e?.name,date:t.date,period:t.period,method:t.method,amount:t.amount,note:t.note,status:t.reversed?'Reversed':'Posted',created_at:t.createdAt}}
function exportSummary(name){const s=companySummary(state,period);downloadCsv(`${name}-${period}.csv`,s.rows.map(r=>({period,employee_id:r.employee.employeeCode,employee:r.employee.name,salary:r.salary,advances:r.advances,adjustments:r.adjustments,final_payable:r.payable,amount_paid:r.paid,status:r.status})))}
function downloadCsv(name,rows){if(!rows.length)return toast('There is no data to export.');const keys=Object.keys(rows[0]);const q=v=>`"${String(v??'').replaceAll('"','""')}"`;download(name,'\ufeff'+[keys.map(q).join(','),...rows.map(r=>keys.map(k=>q(r[k])).join(','))].join('\n'),'text/csv')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
async function importEmployees(e){const file=e.target.files[0];if(!file)return;try{const lines=(await file.text()).trim().split(/\r?\n/);const cells=line=>line.split(',').map(x=>x.trim().replace(/^"|"$/g,''));const headers=cells(lines.shift()).map(x=>x.toLowerCase());let count=0;for(const line of lines){if(!line.trim())continue;const vals=cells(line),row=Object.fromEntries(headers.map((h,i)=>[h,vals[i]]));addEmployee(state,{name:row.name||row.employee,monthlySalary:row.monthly_salary||row.salary,joiningDate:row.joining_date||today(),mobile:row.mobile,department:row.department,notes:row.notes});count++}save();toast(`${count} employees imported`);render()}catch(err){toast(`Import stopped: ${err.message}`)}e.target.value=''}
async function restoreBackup(e){const file=e.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());if(!Array.isArray(incoming.employees)||!Array.isArray(incoming.transactions)||!Array.isArray(incoming.settlements))throw new Error('Invalid backup structure');if(confirm('Replace all data on this device with this backup?')){state={...emptyState(),...incoming};save();render();toast('Backup restored')}}catch(err){toast(`Restore failed: ${err.message}`)}e.target.value=''}

$('#nav').addEventListener('click',e=>{const b=e.target.closest('button');if(b)go(b.dataset.page)});$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#periodPicker').addEventListener('change',e=>{period=e.target.value||currentPeriod();render()});$('.modal-close').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal'||e.target.closest('.modal-cancel'))closeModal();const form=e.target.closest('#employeeForm');if(form&&e.target.type==='submit'){e.preventDefault();const data=Object.fromEntries(new FormData(form));try{const existing=state.employees.find(x=>x.id===data.id);if(existing){const oldSalary=existing.monthlySalary;Object.assign(existing,{name:data.name.trim(),monthlySalary:Number(data.monthlySalary),joiningDate:data.joiningDate,mobile:data.mobile.trim(),department:data.department.trim(),notes:data.notes.trim(),active:data.active==='on',updatedAt:new Date().toISOString()});if(oldSalary!==existing.monthlySalary)state.salaryHistory.push({id:`sal_${Date.now()}`,employeeId:existing.id,salary:existing.monthlySalary,effectivePeriod:period,createdAt:new Date().toISOString()})}else addEmployee(state,data);save();closeModal();render();toast(existing?'Employee updated':'Employee added')}catch(err){toast(err.message)}}const sf=e.target.closest('#settlementForm');if(sf&&e.target.type==='submit'){e.preventDefault();try{const d=Object.fromEntries(new FormData(sf));settle(state,d.employeeId,period,d);save();closeModal();render();toast('Settlement snapshot saved')}catch(err){toast(err.message)}}});
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim(),out=$('#searchResults');const found=q?state.employees.filter(x=>`${x.name} ${x.employeeCode}`.toLowerCase().includes(q)).slice(0,5):[];out.innerHTML=found.map(e=>`<div class="search-result" data-search-id="${e.id}">${person(e)}</div>`).join('')||'<div class="search-result subtle">No employees found</div>';out.classList.toggle('show',!!q)});$('#searchResults').onclick=e=>{const row=e.target.closest('[data-search-id]');if(row){ledgerModal(row.dataset.searchId);$('#searchResults').classList.remove('show');$('#globalSearch').value=''}};
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {});
render();
